1. Добавлена папка tests с выполненными заданиями проекта (6 тестовых…
Canonner/Sprint_5 pull request #1
Opened 2023-10-04 06:58 UTC by Canonner

1. Добавлена папка tests, содержащая 6 файлов с выполненными тестовыми заданиями, файл conftest.py  с фикстурами, файл locators.py с локаторами
2. Добавлена описание проекта в README.md
3. Добавлены игнорируемые файлы в .gitignore

2023-10-06 21:24 UTC, kadirovgm requested changes

2023-10-06 21:24 UTC, kadirovgm commented on tests/conftest.py
> +    browser.get('https://stellarburgers.nomoreparties.site/')
Можно лучше: тестовые статичные данные лучше выносить в отдельный файл типа [data.py](http://data.py/) или [urls.py](http://urls.py/)
Это нужно для легкой поддержке проекта и переиспользовании тестовых данных, мы должны стремиться к тому, чтобы разделять код и тестовые данные, тем самым избегая повторений.

2023-10-06 21:24 UTC, kadirovgm commented on tests/conftest.py
> +    service = Service(ChromeDriverManager().install())
можно лучше: можно ведь было обойтись и без этого?

пример:
```
@pytest.fixture()
def driver():
    driver = webdriver.Chrome()
    driver.get(<url main page>)

    yield driver
    driver.quit()
```

2023-10-06 21:24 UTC, kadirovgm commented on tests/conftest.py
> +def reg_data():
нужно исправить: молодец, что тестовые данные хранишь в едином месте, но их не стоит передавать через фикстуру

для этого лучше создать файл типа data.py или urls.py и там хранить классы данных, которые можно будет переиспользовать в тестах

2023-10-06 21:24 UTC, kadirovgm commented on tests/conftest.py
> +def sign_in(driver):
отлично! вот авторизация как фикстура отлично подходит)

2023-10-06 21:24 UTC, kadirovgm commented on tests/conftest.py
> +    driver.find_element(*Locators.EMAIL_INPUT_FIELD_AUTH).send_keys('test_user_burgers123@ya.ru')
можно лучше: все эти данные, в том числе креды вынеси в data.py

2023-10-06 21:24 UTC, kadirovgm commented on tests/locators.py
> +class Locators:
- Можно лучше: класс с локаторами лучше разделить на несколько: например `AuthPageLocators`, `MainPageLocators`
Сейчас это не критично, но в будущем это точно стоит сделать, так как таким образом ты не будешь импортить лишние локаторы в файл с тестами на экран авторизации. Т.е. у каждой страницы должен быть свой класс с локаторами.
    
    При таком подходе код станет лаконичнее, легко поддерживаемой. Ведь у экрана авторизации и у экрана главной могут быть свои NEXT_BUTTON например. Тогда можно будет легко оба обозвать именно так:
    `MainPageLocators.NEXT_BUTTON` и `AuthPageLocators.NEXT_BUTTON`

2023-10-06 21:24 UTC, kadirovgm commented on tests/test_access_profile.py
> +    # проверка перехода в Личный кабинет с главной страницы по клику на кнопку «Личный кабинет»
можно лучше: для таких комментов можно использовать метод "докстринг"

2023-10-07 18:45 UTC, Canonner commented on tests/conftest.py
> +    service = Service(ChromeDriverManager().install())
Согласен, исправлено, удалено лишнее.

2023-10-07 21:34 UTC, Canonner commented on tests/conftest.py
> +    browser.get('https://stellarburgers.nomoreparties.site/')
Удалил неиспользуемые строки кода. 
Вынес 'https://stellarburgers.nomoreparties.site/' в data.py

2023-10-07 21:50 UTC, Canonner commented on tests/conftest.py
> +def reg_data():
Исправлено. Чтобы не передавать через фикстуру, метод, генерирующий псевдорандомно данные для регистрации,  перенесен в data.py как статический метод. В файле test_registration.py исправлено обращение к нему как к функции.

2023-10-07 21:51 UTC, Canonner commented on tests/conftest.py
> +    driver.find_element(*Locators.EMAIL_INPUT_FIELD_AUTH).send_keys('test_user_burgers123@ya.ru')
Исправлено, тестовые данные вынесены в data.py

2023-10-07 23:56 UTC, Canonner commented on tests/locators.py
> +class Locators:
Реально полезное замечание, спасибо! ))
Исправлено, класс разделен на несколько классов, исправлены все локаторы во всех тестовых файлах.

Жаль что в задании на проект этот момент прописан так, что возникает очень много вопросов.
Я бы сказал, там довольно провокационно сказано, что локаторы надо описать в отдельном файле, но не сказано, как именно, и это, готов поспорить, вызывает одни и те же ошибки у многих студентов, на которые ревьюверу приходится писать одинаковые комментарии ;)
Наставник показывал нам на вебинаре, как решить этот вопрос, но он оформлял это как единый класс и не проговорился про разделение на несколько классов.
Понятно, что про локаторы говорится в следующем спринте, в POM, но возможно, если по этому вопросу будет регулярно набираться некая критическая масса одинаковых комментариев, то стоит подсветить авторам курса - похоже, вы тут не так хорошо объяснили теорию или задание.

Прошу прощения, если я лезу не в свое дело))

2023-10-08 00:27 UTC, Canonner commented on tests/test_access_profile.py
> +    # проверка перехода в Личный кабинет с главной страницы по клику на кнопку «Личный кабинет»
Исправлено, использован docstring

2023-10-09 12:08 UTC, kadirovgm commented on tests/locators.py
> +class Locators:
все верно! да, сейчас мой коммент скорее дополнение и не требуется так делать на этом этапе, в следующем спринте, когда будут говорить про POM, как раз это должно быть

2023-10-09 12:10 UTC, kadirovgm approved these changes

2023-10-09 12:10 UTC, kadirovgm commented on tests/data.py
> +    def reg_data():
супер!

2023-10-09 12:10 UTC, kadirovgm commented on tests/data.py
> +    main_url = 'https://stellarburgers.nomoreparties.site/'
тоже можно было в отдельный класс засунуть, например Credits

2023-10-09 12:10 UTC, kadirovgm commented on tests/locators.py
> +
отлично!

2023-10-10 07:15 UTC, merged